"""
条码插件模板配置文件
定义插件的配置项和默认值
"""

from app.config.barcode_plugin_config import ConfigItem, ConfigItemType


# 定义插件配置项
PLUGIN_CONFIG_DEFINITIONS = [
    ConfigItem(
        key="enabled_types",
        title="启用的条码类型",
        type_=ConfigItemType.LIST,
        default=["ALL_TYPES"],
        description="要检测的条码类型列表"
    ),
    ConfigItem(
        key="min_length",
        title="最小长度",
        type_=ConfigItemType.INTEGER,
        default=1,
        min_value=1,
        max_value=1000,
        description="条码内容最小长度"
    ),
    ConfigItem(
        key="max_length",
        title="最大长度",
        type_=ConfigItemType.INTEGER,
        default=1000,
        min_value=1,
        max_value=10000,
        description="条码内容最大长度"
    ),
    ConfigItem(
        key="include_keywords",
        title="包含关键词",
        type_=ConfigItemType.LIST,
        default=[],
        description="条码内容必须包含的关键词列表"
    ),
    ConfigItem(
        key="exclude_keywords",
        title="排除关键词",
        type_=ConfigItemType.LIST,
        default=[],
        description="条码内容必须排除的关键词列表"
    ),
    ConfigItem(
        key="include_regex",
        title="包含正则表达式",
        type_=ConfigItemType.STRING,
        default="",
        description="条码内容必须匹配的正则表达式"
    ),
    ConfigItem(
        key="exclude_regex",
        title="排除正则表达式",
        type_=ConfigItemType.STRING,
        default="",
        description="条码内容必须排除的正则表达式"
    ),
    ConfigItem(
        key="output_dir",
        title="输出目录",
        type_=ConfigItemType.STRING,
        default="",
        description="拆分后文件的输出目录"
    ),
    ConfigItem(
        key="use_barcode_filename",
        title="使用条码值作为文件名",
        type_=ConfigItemType.BOOLEAN,
        default=True,
        description="是否使用条码值作为输出文件的文件名"
    ),
    ConfigItem(
        key="filename_template",
        title="文件名模板",
        type_=ConfigItemType.STRING,
        default="{barcode}_{index}",
        description="输出文件名的模板，支持变量：{barcode}, {index}"
    ),
    ConfigItem(
        key="duplicate_handling",
        title="重复条码处理",
        type_=ConfigItemType.ENUM,
        default="separate",
        options_list=["merge", "separate"],
        description="重复条码的处理方式：merge(合并为同一文件)或separate(创建单独文件)"
    ),
    ConfigItem(
        key="multi_barcode_handling",
        title="多条码处理",
        type_=ConfigItemType.ENUM,
        default="first",
        options_list=["first", "duplicate_page"],
        description="一页包含多个条码时的处理方式：first(以第一个为准)或duplicate_page(一页复制N次)"
    ),
    ConfigItem(
        key="enable_rotation",
        title="启用旋转检测",
        type_=ConfigItemType.BOOLEAN,
        default=True,
        description="是否启用多角度条码检测"
    ),
    ConfigItem(
        key="max_barcode_count",
        title="最大条码数量",
        type_=ConfigItemType.INTEGER,
        default=100,
        min_value=1,
        max_value=1000,
        description="单次检测的最大条码数量"
    ),
    ConfigItem(
        key="min_confidence",
        title="最小置信度",
        type_=ConfigItemType.FLOAT,
        default=0.5,
        min_value=0.0,
        max_value=1.0,
        description="检测结果的最小置信度阈值"
    )
]